FROM arm64v8/ubuntu:latest


# Install dependencies for Rust development
RUN apt-get update && apt-get install -y \
  build-essential \
  pkg-config \
  libssl-dev \
  jq \
  curl \
  unzip \
  git \
  zip \
  wget \
  python3 \
  xz-utils \
  clang \
  cmake \
  libgtk-3-dev \
  gcc-aarch64-linux-gnu \
  binutils-aarch64-linux-gnu \
  libstdc++6 \
  ca-certificates \
  fonts-dejavu \
  bash-completion \
  && apt-get clean

# Install Rust compiler (using rustup)
RUN curl -sSL https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:$PATH"

WORKDIR /opt
RUN git clone https://github.com/flutter/flutter.git -b stable --depth 1

ENV PATH="/opt/flutter/bin:/opt/flutter/bin/cache/dart-sdk/bin:$PATH"
RUN git config --global http.postBuffer 524288000

# Clone the Dart repository from GitHub (with shallow clone to reduce size)
RUN git clone --depth 1 https://github.com/dart-lang/sdk.git dart

WORKDIR /opt/dart

# Build Dart from source
RUN ./tools/build.py --mode release --arch arm64

# Set the path for Dart binaries
ENV PATH="/opt/dart/out/ReleaseXARM64/dart-sdk/bin:$PATH"

# Verify Dart installation
RUN dart --version
RUN flutter doctor
# Copy the folder from root
COPY src/* /app/

# Change directory
WORKDIR /app/cargokit/build_tool/bin

RUN pwd

RUN ls

RUN mkdir -p ~/lib/linux

RUN mkdir -p  ~/release/linux

RUN which aarch64-linux-gnu-gcc

RUN export CC=aarch64-linux-gnu-gcc
RUN export AR=aarch64-linux-gnu-ar
RUN export RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc"

RUN CARGOKIT_ROOT_PROJECT_DIR="/app/*/" \
CARGOKIT_TARGET_PLATFORM="linux-arm64" \
CARGOKIT_CONFIGURATION="release" \
CARGOKIT_TARGET_TEMP_DIR="/root/lib/linux" \
CARGOKIT_MANIFEST_DIR="/app/rust" \
CARGOKIT_OUTPUT_DIR="/root/release/linux" \
dart run build_tool build-cmake


# Run cargo ndk with aarch64 target
WORKDIR /root/release/linux

RUN pwd

RUN ls
# Run a tiny program to make the build runnable
CMD ["sleep", "infinity"]