FROM ubuntu:latest

# Install dependencies for Rust development
RUN apt-get update && apt-get install -y \
  build-essential \
  pkg-config \
  libssl-dev \
  jq \
  curl \
  unzip \
  git \
  zip \
  wget \
  xz-utils \
  clang \
  cmake \
  libgtk-3-dev \
  libstdc++6 \
  ca-certificates \
  fonts-dejavu \
  bash-completion \
  && apt-get clean

# Install Rust compiler (using rustup)
RUN curl -sSL https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:$PATH"
# Copy the folder from root
COPY src/* /app/

# Change directory
WORKDIR /app/rust/

RUN mkdir -p ~/lib/linux

RUN mkdir -p  ~/release/linux

RUN rustup target add x86_64-unknown-linux-gnu
RUN cargo build --release --target x86_64-unknown-linux-gnu

WORKDIR /
RUN ls
RUN mkdir -p ~/release/output_binaries
ENV SOURCE_DIR="/app/rust/target/x86_64-unknown-linux-gnu/release/"
ENV DEST_DIR="/root/release/output_binaries"

RUN find "$SOURCE_DIR" -maxdepth 1 -type f -name "*.so" -exec cp {} "$DEST_DIR" \; -quit

# Run a tiny program to make the build runnable
CMD ["sleep", "infinity"]