FROM ubuntu:22.04 AS builder
 
# Install dependencies for Rust development
RUN apt-get update && apt-get install -y \
  build-essential \
  pkg-config \
  libssl-dev \
  jq \
  curl \
  unzip \
  git \
  wget \
  clang \
  cmake \
  gcc-arm-linux-gnueabi \
  openjdk-21-jdk \
  && apt-get clean

# Install Rust compiler (using rustup)
RUN curl -sSL https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"

ENV RUST_VERSION="1.81.0"

RUN rustup install "$RUST_VERSION"

RUN rustup default "$RUST_VERSION"

# Install cargo-ndk
RUN cargo install cargo-ndk


# Install Android SDK
WORKDIR /usr/lib
RUN mkdir -p android-sdk
WORKDIR /usr/lib/android-sdk
RUN curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o cmdline-tools.zip \
  && unzip cmdline-tools.zip -d cmdline-tools \
  && mv cmdline-tools/cmdline-tools cmdline-tools/latest \
  && rm cmdline-tools.zip

# Set up Android SDK environment variables
ENV ANDROID_HOME="/usr/lib/android-sdk"
ENV PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

# Accept Android SDK licenses
RUN yes | sdkmanager --licenses

# Install Android NDK
RUN sdkmanager --install "ndk;25.1.8937393"

# Set up NDK environment variables
ENV ANDROID_NDK_HOME="$ANDROID_HOME/ndk/25.1.8937393"
ENV PATH="$ANDROID_NDK_HOME:$PATH"

# Configure Rust cross-compilation
ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=clang
ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_RUSTFLAGS="-C link-arg=-fuse-ld=lld"

# Copy the source code into the container

COPY src/* /app/

WORKDIR /app/rust

RUN rustup target install armv7-linux-androideabi
# Install dependencies and build Rust project with cargo-ndk
RUN mkdir -p /root/release/linux && \
    cargo ndk -t armeabi-v7a build --release 
    

# List the files to verify the build
WORKDIR /app/rust/target/armv7-linux-androideabi/release

RUN cp -r /app/rust/target/armv7-linux-androideabi/release/* /root/release/linux/

RUN mkdir -p ~/release/output_binaries
ENV SOURCE_DIR="/app/rust/target/armv7-linux-androideabi/release/"
ENV DEST_DIR="/root/release/output_binaries"

RUN find "$SOURCE_DIR" -maxdepth 1 -type f -name "*.so" -exec cp {} "$DEST_DIR" \; -quit

FROM ubuntu:22.04 AS final
RUN mkdir -p ~/release/output_binaries
COPY --from=builder /root/release/output_binaries/*.so /root/release/output_binaries

# Keep the container running
CMD ["sleep", "infinity"]
