FROM ubuntu:latest

# Install dependencies for Rust development
RUN apt-get update && apt-get install -y \
  build-essential \
  pkg-config \
  libssl-dev \
  jq \
  curl \
  unzip \
  git \
  zip \
  wget \
  xz-utils \
  clang \
  cmake \
  libgtk-3-dev \
  libstdc++6 \
  ca-certificates \
  fonts-dejavu \
  bash-completion \
  && apt-get clean

# Install Rust compiler (using rustup)
RUN curl -sSL https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:$PATH"

WORKDIR /opt
RUN git clone https://github.com/flutter/flutter.git -b master --depth 1
ENV PATH="/opt/flutter/bin:/opt/flutter/bin/cache/dart-sdk/bin:$PATH"
# RUN cd /opt/flutter && git remote update --prune
# RUN cd /opt/flutter && git fetch --all
# RUN cd /opt/flutter && git checkout stable
RUN flutter doctor

# Copy the folder from root
COPY src/* /app/

# Change directory
WORKDIR /app/cargokit/build_tool/bin

RUN pwd

RUN ls

RUN mkdir -p ~/lib/linux

RUN mkdir -p  ~/release/linux


RUN CARGOKIT_ROOT_PROJECT_DIR="/app/*/" \
CARGOKIT_TARGET_PLATFORM="linux-x64" \
CARGOKIT_CONFIGURATION="release" \
CARGOKIT_TARGET_TEMP_DIR="/root/lib/linux" \
CARGOKIT_MANIFEST_DIR="/app/rust" \
CARGOKIT_OUTPUT_DIR="/root/release/linux" \
dart run build_tool build-cmake


# Run cargo ndk with aarch64 target
WORKDIR /root/release/linux

RUN pwd

RUN ls
# Run a tiny program to make the build runnable
CMD ["sleep", "infinity"]